-- Add new role values only (UPDATE statements must be in a separate migration)
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FINANCE_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'ASSISTANT_MANAGER_BILLING';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SENIOR_OFFICE_PAYMENTS';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SENIOR_ARAP_OFFICER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PAYMENT_OFFICER';
