export declare enum Role {
    SUPER_ADMIN = "SUPER_ADMIN",
    OWNER = "OWNER",
    FINANCE_MANAGER = "FINANCE_MANAGER",
    ASSISTANT_MANAGER_BILLING = "ASSISTANT_MANAGER_BILLING",
    SENIOR_OFFICE_PAYMENTS = "SENIOR_OFFICE_PAYMENTS",
    SENIOR_ARAP_OFFICER = "SENIOR_ARAP_OFFICER",
    PAYMENT_OFFICER = "PAYMENT_OFFICER"
}
export declare const TENANT_ROLES: readonly [Role.OWNER, Role.FINANCE_MANAGER, Role.ASSISTANT_MANAGER_BILLING, Role.SENIOR_OFFICE_PAYMENTS, Role.SENIOR_ARAP_OFFICER, Role.PAYMENT_OFFICER];
export declare const APPROVAL_ROLES: readonly [Role.OWNER, Role.FINANCE_MANAGER, Role.ASSISTANT_MANAGER_BILLING];
//# sourceMappingURL=roles.d.ts.map